/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorReporte;
import javax.swing.JPanel;

/**
 *
 * @author Jose
 */
public class JDialogReporte extends javax.swing.JDialog implements TienePassword  {

    ControladorReporte controladorReporte;
    
    public JDialogReporte(java.awt.Frame parent, boolean modal, ControladorReporte controladorReporte) {
        super(parent, modal);
        this.controladorReporte = controladorReporte;
        initComponents();
        
        this.setVistaPassword();
    }
    
    @Override
    public void vistaPrincipal() {
        this.setVistaReporte();
    }
    
    public void setVistaReporte() {
        VistaFormReporte vfr = new VistaFormReporte(this.controladorReporte);
        this.cambiarVista(vfr);
    }
    
    public void setVistaPassword() {
        VistaPassword vistaPassword = new VistaPassword(this);
        this.cambiarVista(vistaPassword);
    }
    
    private void cambiarVista(JPanel panel) {
        this.jPanelPrincipal.removeAll();
        this.jPanelPrincipal.add(panel);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
